<?php

namespace DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    /**
     * @param $name
     *
     * @return City[]
     */
    public function search($name)
    {
        return $this->createQueryBuilder('city')
            ->where('city.name LIKE :name')
            ->setParameter('name', $name . '%')
            ->getQuery()
            ->getResult();
    }
}
