<?php

namespace DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WarehouseRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class WarehouseRepository extends EntityRepository
{
    /**
     * @param $city
     *
     * @return Warehouse[]
     */
    public function search($city)
    {
        return $this->createQueryBuilder('warehouse')
            ->where('warehouse.city = :city')
//            ->andWhere('warehouse.type = :type')
            ->setParameters([
                'city' => $city
            ])
            ->getQuery()
            ->getResult();
    }
}
