imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - SonataFormatterBundle:Form:formatter.html.twig
    globals:
      shop_name: %shop_name%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        logging: true
        profiling: true

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port: 587
    encryption: tls
    spool:
      type: file
      path: "%kernel.root_dir%/spool"

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

        twig:
            service: sonata.formatter.text.twigengine
            extensions: []

sonata_admin:
    templates:
        layout:  SonataAdminBundle::layout.html.twig

ivory_ck_editor:
    default_config: default
    configs:
        default:
            # default toolbar plus Format button
            toolbar:
            - [Bold, Italic, Underline, -, Cut, Copy, Paste, PasteText, PasteFromWord, -, Undo, Redo, -, NumberedList, BulletedList, -, Outdent, Indent, -, Blockquote, -, Image, Link, Unlink, Table]
            - [Format, Maximize, Source]

#            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
#            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
#            # Display images by default when clicking the image dialog browse button
#            filebrowserImageBrowseRouteParameters:
#                provider: sonata.media.provider.image
#            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
#            filebrowserUploadRouteParameters:
#                provider: sonata.media.provider.file
#            # Upload file as image when sending a file from the image dialog
#            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
#            filebrowserImageUploadRouteParameters:
#                provider: sonata.media.provider.image
#                context: my-context # Optional, to upload in a custom context

sonata_user:
    security_acl: false
    manager_type: orm
    class:
      user: UserBundle\Entity\User
      group: UserBundle\Entity\Group

sonata_block:
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class: UserBundle\Entity\User
    group:
      group_class: UserBundle\Entity\Group