categories_show:
    path:     /categories/{alias}
    defaults: { _controller: CategoryBundle:Category:show }

categories_list:
    path:     /categories
    defaults: { _controller: CategoryBundle:Category:list }
