services:
  sonata.admin.category:
    class: CategoryBundle\Admin\Entity\CategoryAdmin
    tags:
        - { name: sonata.admin, manager_type: orm, group: "Category", label: "Category" }
    arguments:
        - ~
        - CategoryBundle\Entity\Category
        - ~